### PR TITLE
apply lock to all TestOutput API

### LINKED ISSUE #16: Race in testOutput.recordError
```
==================
WARNING: DATA RACE
Read at 0x00c0004880f0 by goroutine 29:
  github.com/orbs-network/scribe/log.(*TestOutput).HasErrors()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/scribe@v0.2.1/log/test_output.go:73 +0x7b
  github.com/orbs-network/orbs-network-go/test/with.RequireNoUnexpectedErrors()
      /Users/shaiyallin/dev/orbs-network-go/test/with/logging.go:39 +0x42
  github.com/orbs-network/orbs-network-go/test/with.Logging()
      /Users/shaiyallin/dev/orbs-network-go/test/with/logging.go:27 +0x532
  github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.TestDirectIncoming_ConnectionsAreListenedToWhileContextIsLive()
      /Users/shaiyallin/dev/orbs-network-go/services/gossip/adapter/tcp/server_test.go:22 +0x67
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163

Previous write at 0x00c0004880f0 by goroutine 31:
  github.com/orbs-network/scribe/log.(*TestOutput).recordError()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/scribe@v0.2.1/log/test_output.go:94 +0x9d
  github.com/orbs-network/scribe/log.(*TestOutput).Append()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/scribe@v0.2.1/log/t.go:29 +0x208
  github.com/orbs-network/scribe/log.(*basicLogger).Log()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/scribe@v0.2.1/log/logger.go:103 +0x5e6
  github.com/orbs-network/scribe/log.(*basicLogger).Error()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/scribe@v0.2.1/log/logger.go:112 +0x83
  github.com/orbs-network/orbs-network-go/instrumentation/logfields.(*govnrErrorer).Error()
      /Users/shaiyallin/dev/orbs-network-go/instrumentation/logfields/govnr_error_handler.go:18 +0x3ff
  github.com/orbs-network/govnr.recoverPanics()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/panic.go:24 +0x105
  runtime.call32()
      /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:519 +0x3a
  github.com/orbs-network/govnr.tryOnce()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/panic.go:19 +0x68
  github.com/orbs-network/govnr.Once.func1()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/once.go:27 +0x4c

Goroutine 29 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:916 +0x65a
  testing.runTests.func1()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1157 +0xa8
  testing.tRunner()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:865 +0x163
  testing.runTests()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1155 +0x523
  testing.(*M).Run()
      /usr/local/Cellar/go/1.12.6/libexec/src/testing/testing.go:1072 +0x2eb
  main.main()
      _testmain.go:92 +0x222

Goroutine 31 (running) created at:
  github.com/orbs-network/govnr.Once()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/once.go:26 +0x60
  github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*transportServer).mainLoop()
      /Users/shaiyallin/dev/orbs-network-go/services/gossip/adapter/tcp/server.go:153 +0x788
  github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*transportServer).startSupervisedMainLoop.func1()
      /Users/shaiyallin/dev/orbs-network-go/services/gossip/adapter/tcp/server.go:259 +0x65
  github.com/orbs-network/govnr.tryOnce()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/panic.go:19 +0x68
  github.com/orbs-network/govnr.Forever.func1()
      /Users/shaiyallin/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/forever.go:77 +0x76
==================
```

### PR DESCRIPTION
**Pull request by amir-arad**
fixes #16

### CODE REVIEW

File: log/test_output_test.go [hunk 1]
```diff
@@ -93,6 +93,27 @@ func TestOutputFailsTestEvenAfterTermination(t *testing.T) {
...
+		ch <- struct{}{}
+	}()
+	go func() {
+		for i := 1; i <= 100; i++ {
+			o.HasErrors()
+		}
+		ch <- struct{}{}
+	}()
+	<-ch
+	<-ch
```
Comment (ronnno) [inline log/test_output_test.go]: the test may timeout if an exception is thrown in one of the goroutines, but i'm not sure we will see any meaningful output. did you try `panic` inside one of these for loops to see what it looks like when you fail?

Comment (amir-arad) [reply log/test_output_test.go]: I let the race detector fail this test several times. got a solid true negative statistics before introducing solution.
